openapi: 3.1.0
info:
  title: MenuGen API
  description: Backend API for MenuGen - AI-powered menu visualization
  version: 1.0.0
servers:
  - url: /api
    description: API base path
paths:
  /process-menu:
    post:
      summary: Process menu image with AI
      description: Upload a menu image and get AI-generated dish descriptions and images
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: Menu image file
                openaiKey:
                  type: string
                  description: OpenAI API key
              required:
                - image
                - openaiKey
      responses:
        '200':
          description: Successfully processed menu
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the dish
                        description:
                          type: string
                          description: Description of the dish
                        image_url:
                          type: string
                          description: Generated image URL for the dish
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
